### ISSUE TITLE
Allow to block VP9 in Settings, use AVC as default for mp4

### ISSUE THREAD

**Issue by rmayergfx** [ErrorFlynn/ytdlp-interface#102]
YT uses VP9 and AV1 for higher quality videos, ext for VP9 is sometimes webm, sometimes mp4.
Is it possible to force AVC for mp4?

![grafik](https://github.com/ErrorFlynn/ytdlp-interface/assets/105392164/1940706d-1c03-4532-943c-9938a703370f)

**Comment by rmayergfx** [comment]
Found a temp solution, add following to the Custom arguments:

` --restrict-filenames -S "+codec:h264"`

**Comment by ErrorFlynn** [comment]
Yes, I'm aware of the issue (it has been bothering me as well). The next version (probably coming out in a week or two) will allow the user to set a preferred video codec.
