### ISSUE TITLE
[Feature Request]   Modified 'error'-handling:  'repeat'-button or automatic loop

### ISSUE THREAD

**Issue by altadr** [ErrorFlynn/ytdlp-interface#104]
People say, only an insane person repeats an action that has proved successless. 

After some times receiving an 'error' trying to enter an URL,  
first I erratically changed the method (drag&drop, ctrl-c, ctrl-v, ...), 
and sometimes it was successful, and sometimes not. 

After a lot of trial and error I did not find any systematical conclusion or solution to this problem. 

Then I switched to do, what is known as totally useless, 
I simply repeated exactly what had proven successless. 
Not only once, but sometimes more than 10 times. 

And in every case I got an 'error', and an 'error' again, and again and again. 

But suddenly, without any alteration of the procedure, a 'queued' appeared.   

This worked for all URLs I tried, sometimes after 3 or 4 attempts, 
in few cases it needed more than 10, but it was in the end always successful. 

Only, it is really annoying having to first remove the unsuccessful item, 
then reentering the same URL, receiving the 'error' 
and knowing having to repeat this loop an unforseeable number of repetations.    

Is it easyer to implement a new 'repeat'-button, 
or, 
even more comfortable for the user,  
a simple loop repeating up to 20 times before ending 
(and showing 'error' if still no success, but that never occurred during my trials) ...

Thank you very much!

**Comment by ErrorFlynn** [comment]
Is the error from yt-dlp `Incomplete data received`? I've been getting that for YouTube playlists, and I've already implemented a workaround. I think I will also add a refresh command to the context menu.

**Comment by altadr** [comment]
Just having written the above, now I eperienced for the first time 
a case that could not be solved by only repeating the entering process: 
  
Here the problem was, that one members-only-video was in the playlist. 

So the problem here could be solved (incomplete) 
by opening the original URL in the browser 
and entering every single video's URL separately from there
(besides the one for members only). 

For such cases another command in the context menu could be helpful, too:

'copy the original URL to the clipboard', 

and maybe even a third one: 

'open the original URL in the browser'

**Comment by altadr** [comment]
And, yes, the most errors resulted from 'Incomplete data received'.

**Comment by ErrorFlynn** [comment]
You can now update to the latest version of yt-dlp on the nightly release channel, to get rid of the `Incomplete data received` error.

**Comment by altadr** [comment]
Thank you very much!
