### ISSUE TITLE
GUI not responding 

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#107]
while downloading, pressing X to close the GUI, does not work.
Instead of closing the window, I get (Not responding)
![2023-10-11_01h22_52](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/66c795c1-f23b-4bac-abe0-4b7338d53cc3)

after force closing, the main window is closed, but some yt-dlp.exe and conhost.exe instances remain alive:
![2023-10-11_01h25_23](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/f5e4d8c3-a25c-4733-82b5-aa27aecb1dfd)

**Comment by ErrorFlynn** [comment]
Update to v2.8.0 and let me know if this still happens!
