### ISSUE TITLE
Unable to download from Arte

### ISSUE THREAD

**Issue by Strabisme** [ErrorFlynn/ytdlp-interface#11]
Hi !

Trying to downlaod a film on Arte leaves me with

`ERROR: [ArteTV] 063571-000-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>);`

I wasn't able to download a film with the program when I could some days ago. I attempted to download this one https://www.arte.tv/fr/videos/063571-000-A/la-loi-du-marche/ (it won't be available tomorrow so of course it'll give a 404 but until then it was available but yt-dlp can't dl it.

I don't know if I use the ticket tool correctly, it's my first time.

Thank you and have a nice day !

**Comment by ErrorFlynn** [comment]
Hi, that's an issue with `yt-dlp`, you should probably post it here: https://github.com/yt-dlp/yt-dlp/issues
Or, you could first post it in the subreddit (https://www.reddit.com/r/youtubedl), there are lots of knowledgeable people there, including the main developer.

It sounds like it could be an extractor issue, but I'm not affiliated with the `yt-dlp` project in any way, and I'm not able/qualified to do anything about it. Good luck, I hope you resolve it.

**Comment by ErrorFlynn** [comment]
It looks like what you're reporting is already on the [list of known issues](https://github.com/yt-dlp/yt-dlp/issues/3766): 
https://github.com/yt-dlp/yt-dlp/issues/3622
