### ISSUE TITLE
[Enhancement] Saving config file every time an item is added/removed from the queue

### ISSUE THREAD

**Issue by samuelchristlie** [ErrorFlynn/ytdlp-interface#110]
Having the config file saved whenever an item is added or removed from the queue would be very helpful. Currently, the config file is only saved when the program is closed, which is reasonable for storing the settings. However, the same file also contains information about the queue.

Sometimes, the program would randomly crash and dozens of items in my queue would be gone, My current solution to that is to close the program to save the config file before reopening and starting the download but it's not handy if the downloads are already started.

I think it'd be great if the program saves the config file more often or maybe if it kept a separate file for the queue that's backed up when the queue changes.

**Comment by ErrorFlynn** [comment]
>My current solution to that is to close the program to save the config file before reopening and starting the download but it's not handy if the downloads are already started.

The latest version (2.7.0) allows you to write the settings file at will. Just open the settings window, and click the button at the bottom. A quick way to do that is `Ctrl+S` (open settings), `Ctrl+S` (save), `Esc` (close settings window).

I'll consider adding an option to write the file automatically when queue items are added or removed.
