### ISSUE TITLE
Better Media Sections

### ISSUE THREAD

**Issue by Shiriow** [ErrorFlynn/ytdlp-interface#112]
It would be nice to make selecting media sections a bit easier:

Being able to paste in time.

Use the scrollwheel/arrow keys to quickly add/subtract time.

Related to above, an option to separate hours, minutes and seconds for easier editting; not needing to add ":" or erasing it by mistake.

An option to add the "- section x to y" in the title even with only one section.

**Comment by ErrorFlynn** [comment]
I've added the copy/paste functionality in v2.13 (took me 8 months for some reason, sorry about that). The other suggestions are too much of a headache to implement, I'm afraid. I might revisit the issue at some point, but I'll be focusing on other priorities for now.
