### ISSUE TITLE
Observation, when internet interrupted

### ISSUE THREAD

**Issue by altadr** [ErrorFlynn/ytdlp-interface#113]
Strange things happen, 
when the internet connection is interrupted: 

Knowing about my unreliable internet connection, 
yesterday I observed accidentally what happens, 
when an interruption during a download session occurs.

The running downloads suddenly appear as 'done' in the queue, 
and  .part-files remain in the downloads folder. 

Subsequently the not yet started files get labelled 'done' in quick progress. 

After everything is 'done', and the app is closed, 
consequently the 'ytdlp-interface.json' file 
does not contain any 'unfinished_queue_items', 
everything was considered 'done' and so all is lost. 

(That explains, why I sometimes see 
nothing else than "[ ]" there, 
though knowing that many items 
actually have not yet been done. 
And explains the slowly growing number 
of .part files in the downloads folder. 

These are never being resumed, 
because the URLs in the 'ytdlp-interface.json' file are gone. 
The innocent user relies on the displayed status 'done' 
and wonders where to find the respective downloads, 
desperately searching and searching and ... 

Actually in this case it can be easy 
to retrieve if the ID is saved in the filenames 
of the .part files and to try again downloading. 

Unlike the not yet started downloads, 
the info regarding these vanishes traceless ... )

PS
Sorry for the length, 
this only mirrors the relief 
that I got from this observation 
and now having an idea concerning 
the mystery of the never found files ...

**Comment by altadr** [comment]
Today having started the app without noticing before, 
that my internet connection was down, 
resulted in 'error' status of all items in the queue, 
empty download list in 'ytdlp-interface.json' 
after shutting down the app and an empty queue after restart. 

As a possibe simple solution I could imagine, 
before writing a new version of 'ytdlp-interface.json' 
automatically adding a number or date 
to the filename of the existing one
(that by this now is archived in a versionized form) 
could make it much easyer to retrieve former 
lost versions of the download queue 
in 'ytdlp-interface.json' and their history ...

Thank you very much 
for this great app and your effort, 
and best wishes for a happy, healthy and peaceful 
new year!

**Comment by ErrorFlynn** [comment]
Version 2.8.0 now sets the queue status to "error" instead of "done" when a download fails, and also lets you save the queue items with "error" status (option in Settings->Queue).
