### ISSUE TITLE
FINALLY!

### ISSUE THREAD

**Issue by BeegDeek** [ErrorFlynn/ytdlp-interface#115]
THE BEST! THE ONLY ONE THAT WORKS WITHOUT GOING THROUGH SHITTY STEPS!

**Comment by mid-ff-play17** [comment]
> THE BEST! THE ONLY ONE THAT WORKS WITHOUT GOING THROUGH SHITTY STEPS!

This is something like a review of the program?

**Comment by BeegDeek** [comment]
YES! IT KICKS BUTT!

**Comment by Azertyyys** [comment]
> THE BEST! THE ONLY ONE THAT WORKS WITHOUT GOING THROUGH SHITTY STEPS!


I understand that you enjoyed the program but please don't open an issue for writing a review
