### ISSUE TITLE
[Bug] Manually selected Formats don't update in main panel Formats column

### ISSUE THREAD

**Issue by githottub** [ErrorFlynn/ytdlp-interface#118]
Firstly, thank you for continuing to update and improve ytdlp-interface. It is much appreciated. 

Bug: If I right-click on a youtube link, choose Select formats, manually select the audio and video formats I want, then click the Use the selected format(s) button... those manually selected formats are not updated in the Format column on the main interface panel.

UPDATE: I've also occasionally noticed the reverse of the above. For example, the video + audio formats initially indicated in the format column of the main panel do not match what is checked when I go into the format selection panel for the first time. This is just a guess but, this might be happening in situations when I've previously checked a Youtube link to see if they'd added enhanced bitrate to it yet, but the hadn't, so I delete the link then try again later. At that point they've added it so, for example, it will show format 616 in the main panel but that isn't what is checked in the format pane. Maybe that's because the app is remembering what was previously checked for that link before 616 became available. In any case, there are obviously issues that need to be addressed to make sure the formats shown in the main interface pane always match what's shown in the formats pane.

Note: This problem already existed previously and isn't something new in the latest version. I just waited for the 2.8.0 release to see if maybe it would be fixed. Since it hasn't, I figured I should go ahead and report it here.

**Comment by kolbdog3333** [comment]
I hope that will be fixed to its very annoying to see the format not changing when you select the formats

**Comment by ErrorFlynn** [comment]
> I hope that will be fixed to its very annoying to see the format not changing when you select the formats

Yes, that will be part of the next version.

**Comment by githottub** [comment]
> Yes, that will be part of the next version.

Thank you for continuing to improve this great app. It is truly appreciated.
