### ISSUE TITLE
Allow selecting songs and formats & viewing JSON data for errored queue items

### ISSUE THREAD

**Issue by azumukupoe** [ErrorFlynn/ytdlp-interface#119]
Also, it would help if song selection dialog showed which song had errored

**Comment by ErrorFlynn** [comment]
>Allow selecting songs and formats & viewing JSON data for errored queue items

This will be in the next version.

>Also, it would help if song selection dialog showed which song had errored

You can look at the output to see which song errored. Incorporating that info into the song selection window seems like too much trouble, so it's probably not make it into the next version. I'm probably going to just not select the songs preceding the one where the download stopped.
