### ISSUE TITLE
Custom path for FFMpeg and FFProbe binaries in ytdlp-interface

### ISSUE THREAD

**Issue by Bamajon1974** [ErrorFlynn/ytdlp-interface#120]
Good afternoon

Is there a way to have a custom path for ffmpeg and ffprobe binaries in the ytdlp-interface settings? The path to yt-dlp can be set in the ht-dlp section of settings but there is no option to set a path for ffmpeg and ffprobe in the updater section. 

I have ffmpeg binaries installed in a specific folder, (%programfiles%\ffmpeg) yt-dlp installed in another, separate folder (i.e., %programfiles\yt-dlp) so other programs like Foobar and Audacity can all access, and would like ytdlp to access ffmpeg binaries from a that same chosen folder rather than within the same folder where ytdlp-interface is installed. Thus, I wouldn't need two copies of ffmpeg binaries. 

Please advise. Thanks!

**Comment by ErrorFlynn** [comment]
The program doesn't allow specifying a custom path for ffmpeg (this is a yt-dlp issue that should be addressed externally).

To specify a custom ffmpeg path, you have to give yt-dlp the `--ffmpeg-location` argument, which is probably best done using a [config file](https://github.com/yt-dlp/yt-dlp#configuration). Just create `yt-dlp.conf` in the yt-dlp folder, and write your `--ffmpeg-location` in it. I've never tried this myself, but it should work.

**Comment by Bamajon1974** [comment]
Thank you for the reply. I will try the configuration option mentioned above. Do I need to add any specific headers or other information to the header of the configuration file? 

Thanks!

**Comment by ErrorFlynn** [comment]
>Do I need to add any specific headers or other information to the header of the configuration file?

No, just write the argument. For example:
`--ffmpeg-location "C:\Program Files\FFmpeg"`

**Comment by Bamajon1974** [comment]
I have ytdlp-interface and yt-dlp installed in a folder in %programfiles% directory. I have FFMpeg installed in c:\ffmpeg. I created a yt-dlp.conf file with --ffmpeg-location "C:\FFmpeg" in %programfiles%\yt-dlp. 

I also moved the ytdlp-interface, yt-dlp and ffmpeg into user folders (which don't require admin access). 

In both cases, when ytdlp-interface was launched, yt-dlp (which was in the same directory as ytdlp-interface) was found but ffmpeg (which was in a different folder in bothcases) was NOT found. 

Please advise if there is anything else I should do or wait for a update to potentially resolve the issue. 

Thanks!

**Comment by ErrorFlynn** [comment]
>In both cases, when ytdlp-interface was launched, yt-dlp (which was in the same directory as ytdlp-interface) was found but ffmpeg (which was in a different folder in bothcases) was NOT found.

It wasn't found by ytdlp-interface, but that only means you can't use ytdlp-interface to update ffmpeg. Everything else should work normally (yt-dlp will find ffmpeg and use it). I intend to add support for a custom ffmpeg path in the next version, so that ffmpeg files at a custom location can be updated from ytdlp-interface.

**Comment by Bamajon1974** [comment]
Great! Thank you for the update!
