### ISSUE TITLE
[BUG]Website that makes the app crash

### ISSUE THREAD

**Issue by heartdeadz** [ErrorFlynn/ytdlp-interface#121]
Hey there.  i just wanted to report in a website that makes your app crash.
https://tv.nrk.no/serie/oppsynsmannen/sesong/1/episode/1
( any videos on tv.nrk.no ) 
its a local Norwegian video website.
it is supported by yt-dlp ( https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md )
The other local sites over here works flawlessly tho :D  its just tv.nrk.no  that won't work.

i did add it via yt-dlp.gui and other apps  and it works just fine with those.  
figured i'd say something incase you wanted to know! :P 
i do love your UI btw, its absolutely fantastic to look at! 
and i do love its settings and such.
i'd actually wanna use this over the other ones i've tried out :D  but that crash is very unfortunate. 
i was looking for a logs file to attatch, but alas, i could not find one to look at.

**Comment by ErrorFlynn** [comment]
Thanks for reporting this, I found the problem and the next version will contain the fix.

**Comment by heartdeadz** [comment]
That is fantastic! thanks for that! :D
