### ISSUE TITLE
[Bug} File size shown in formats window doesn't match yt-dlp output

### ISSUE THREAD

**Issue by githottub** [ErrorFlynn/ytdlp-interface#123]
Example: 
https://www.youtube.com/watch?v=DfLW4pdvn-s

The ytdlp-interface format window shows video format 315 has file size of 2.27 GB. But running command line of:

yt-dlp --list-formats "https://www.youtube.com/watch?v=DfLW4pdvn-s"

shows video format 315 has file size of 6.27 GB... which is the correct file size of the downloaded file. This is just one example but I have seen similar discrepancies with other youtube videos.

**Comment by ErrorFlynn** [comment]
Thanks for reporting this, I've identified the bug and I'm working on a fix.
