### ISSUE TITLE
[Bug] File size not showing for formats

### ISSUE THREAD

**Issue by githottub** [ErrorFlynn/ytdlp-interface#124]
I've just discovered this with NHK videos; however, I'm not sure if it might also be an issue with other non-youtube sites.

Some example videos:
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2102020/
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066052/
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2029065/

ytdlp-interface does not show file sizes or bitrates for any of the formats on any of these videos - either in the main window or the formats window. However, yt-dlp itself does. 

For example:
yt-dlp --list-formats "https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2102020/"

provides:
ID   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────
529  mp4 320x180     30 │ ~108.61MiB  530k m3u8  │ avc1.42c01f mp4a.40.2
934  mp4 640x360     30 │ ~191.53MiB  935k m3u8  │ avc1.77.30  mp4a.40.2
1606 mp4 1280x720    30 │ ~329.18MiB 1606k m3u8  │ avc1.64001f mp4a.40.2
2422 mp4 1280x720    30 │ ~496.53MiB 2423k m3u8  │ avc1.64001f mp4a.40.2

As you can see, it provides approximate filesize and bitrate info for each format. It would be helpful if this was shown in ytdlp-interface the same way it shows it for youtube videos.

Thank you for the recent 2.9 release. It is a great improvement and truly appreciated.

**Comment by ErrorFlynn** [comment]
The program uses `-j` (aka `--dump-json`) to get video data from yt-dlp. It seems that for those URLs (and some other non-YouTube URLs that I tested), `-j` doesn't produce any filesize info for the formats (the JSON keys `filesize` and `filesize_approx` are absent from the JSON data for those URLS). Unfortunately I don't know why that is, or what to do about it (seems like something that might be worth raising with the yt-dlp developers).

I will look into alternative ways to get the filesize, but I'm not making any promises.

**Comment by ErrorFlynn** [comment]
The total bitrate (TBR) has always been in the JSON data received from yt-dlp, it's just that the program has never displayed it. That was a deliberate decision on my part, because I don't find TBR very useful, but I will change that in the next version.
