### ISSUE TITLE
[Feature Request] Opus as Audio Container

### ISSUE THREAD

**Issue by githottub** [ErrorFlynn/ytdlp-interface#129]
There are millions of youtube videos with Opus audio. When downloading just the audio (i.e. from a music video, concert, etc) it would be preferable to leave it as-is saved as an opus file. There is no requirement to put opus audio into a separate container such as Ogg. Practically every current Windows audio player will play audio files with an .opus extension and Google themselves added that ability to Android many years ago.

**Comment by ErrorFlynn** [comment]
The setting `Preferred audio container` translates to the command line option/argument `-S "aext:<ext>"`, which tells yt-dlp which audio file extension to consider the best. That causes yt-dlp to download a format with the specified file extension, if such a one exists. It does not cause yt-dlp to put the audio stream into a specific container.

The program provides options like `ogg`, `flac`, and `mp3` for non-YouTube sites that may offer those container formats. As far as I can tell, YouTube's opus audio format is always in a .webm container, so the most you can do, is use `-x --audio-format opus` as a custom argument. That causes yt-dlp to mux the audio stream from the downloaded .webm file into an .opus file using ffmpeg, and then delete the .webm file.

**Comment by githottub** [comment]
Thanks for the explanation. Yes, Youtube does download Opus audio in a .webm container. Therefore, I've been manually doing exactly what you described and using ffmpeg to extract the Opus audio and save it as a .opus file... which results in a slightly smaller file and makes it far more recognizeable to most audio players than a webm file. 

The feature request was essentially my hope that ytdlip-interface could automate that process. Thereby, if Opus was set as the Preferred audio container and if only Opus audio (no video) was selected in the formats window then the app would d/l it from Youtube as webm then automatically have ffmpeg extract/save the opus audio. My thinking was that I know I'm not the only one saving the audio track from YT videos and since having it as a .opus file makes it both smaller and more widely playable than .webm, it would be a particularly helpful feature to all the people who have no idea how to use CLI commands to get such a file using ffmpeg manually.

As always, thanks for your consideration and continued improvement of this great app.
