### ISSUE TITLE
replace the output argument

### ISSUE THREAD

**Issue by Flwk** [ErrorFlynn/ytdlp-interface#13]
Hello,

I wanted to download a playlist, and because they were a lot of videos, i wanted to add an index at the beginning of the filename like this ; 

-o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"

But this doesn't work because there is already one "-o" for the destination folder. Is it possible to do something about it ? 

Thank you for your works ! 

Bets regards

**Comment by ErrorFlynn** [comment]
Sure, I'll see what I can do. Thanks for the feedback.

**Comment by TheMrcoin** [comment]
I agree this would be very helpful, I wanted to do the same but had to avoid the ytdlp-interface to do it.
