### ISSUE TITLE
SoundCloud playlist (sets) support

### ISSUE THREAD

**Issue by azumukupoe** [ErrorFlynn/ytdlp-interface#145]
It's supported by yt-dlp itself but not by ytdlp-interface

**Comment by ErrorFlynn** [comment]
The URLs I tested worked for me (for example https://soundcloud.com/soundcloud/sets/origins-john-summit). Can you give an example of a URL that doesn't work?

**Comment by ErrorFlynn** [comment]
Never mind, I understand what the problem is. I'll probably release a patch version soon with the fix.
