### ISSUE TITLE
Keeping download path info

### ISSUE THREAD

**Issue by MiracleIC** [ErrorFlynn/ytdlp-interface#15]
One more issue I wold like to report.
Every time I run the program, I have to choose the folder for downloading a file.  Would it be possible to keep that path for the next time and make drop-down list? No need to use registry, it could be as simple as open a text file with downloading folders history with at least one folder path in it.
However, I would probably make some round number, like 8 or 16 paths :-)

Thanks.

**Comment by ErrorFlynn** [comment]
The program does remember the last used download folder (it stores it in the settings file `ytdlp-interface.json`). If it doesn't for you (your post is ambiguous about that), then something's wrong.

That being said, it's a good idea to remember more than one folder. I myself have two download locations that I occasionally switch between, and it would be easier to switch by choosing from a menu. I'll put this feature on my to-do list, thanks for the feedback.

**Comment by MiracleIC** [comment]
Ahh, yes. the kast one kept in there. I was lately downloading in two folders and when I wanted to switch to the second folder and klicked on the current path it opened the program folder. That is not convenient. Probably because of that I've got an impression that the folder has not been kept.
Thanks that you are going to make some changes in that.
