### ISSUE TITLE
[Suggestion] Replace "download options queue" section to child window

### ISSUE THREAD

**Issue by the-liquid-metal** [ErrorFlynn/ytdlp-interface#155]
At the moment, `download options queue` section does not have a space related problem.

Without careful observation and trial and error, the placement of this section in current location makes new user think that `download options queue` and `select formats` work with different object. At first, i assume that this section applied to all download items, and `Apply options to all items` just ordinary apply button. In reality, the section and `select formats` are work with a single selected download item, and `Apply options to all items` has special task.

If `download options queue` section and `Apply options to all items` button are placed in a child window, alongside with `select formats`, confusion experienced by new users can be minimized. To organize these groups, we can use `tab set` (like `settings` window) to this window. All `select formats` fields are places in `format` tab, and all `download options queue` fields and `Apply options to all items` button are placed in `more options` tab.

There is a plenty of room in this child window if someday we have to place more fields.

If we need fields that don't match a single download item, then we can place those field in the main window in place of the current `download options queue` section.

**Comment by ErrorFlynn** [comment]
>Without careful observation and trial and error, the placement of this section in current location makes new user think that download options queue and select formats work with different object. At first, i assume that this section applied to all download items, and Apply options to all items just ordinary apply button. In reality, the section and select formats are work with a single selected download item, and Apply options to all items has special task.

By default, the `Download options` group **_does_** apply to all queue items. It only applies to just the selected item after you have gone to `Settings->Queuing` and checked `Each queue item has its own download options`. Initially, the group title is `Download options`, but after you check `Each queue item has its own download options`, it becomes `Download options for queue item #n`. I think all this should be enough to communicate to the user when the download options apply to all queue items, and when they apply only to the selected queue item.
