### ISSUE TITLE
[REQUEST] Android client

### ISSUE THREAD

**Issue by Billynom8** [ErrorFlynn/ytdlp-interface#158]
I wonder if you could add a simple option in settings to select the client eg. for yt-dlp.exe "youtube:player_client=android"
I have been looking at all GUI but this feature isn't available.
The reason for the request is because VR180 videos are only available on android client.

here's an example.
yt-dlp --extractor-args "youtube:player_client=all" "a2uOeWkmc88" -F
313 = 2560x2160 (one eye only)

yt-dlp --extractor-args "youtube:player_client=android" "a2uOeWkmc88" -F
313 = 3840x2160 (side by side 2:1)

Obviously this switch is needed for the download too.

Many thanks, appreciate what you do.

**Comment by ErrorFlynn** [comment]
Sure, the next version will have checkbox for using the Android client.
