### ISSUE TITLE
Possibility to download subtitles

### ISSUE THREAD

**Issue by alekssmitt** [ErrorFlynn/ytdlp-interface#160]
is it possible to implement the ability to download subtitles?

**Comment by githottub** [comment]
Have you checked the box in Download options which says "Embed subtitles"? If that doesn't resolve your situation then you need to provide more detail.

**Comment by alekssmitt** [comment]
maybe the embedded subtitles option works but it definitely doesn't with the auto-generated subtitles. besides, there is no possibility to choose the language at all.

**Comment by alekssmitt** [comment]
https://www.youtube.com/watch?v=V6B_DzSjk5s
ok, this one for example has embedded subtitles, no, there are no subtitles in the output file

**Comment by githottub** [comment]
> https://www.youtube.com/watch?v=V6B_DzSjk5s ok, this one for example has embedded subtitles, no, there are no subtitles in the output file

Are you sure??? Youtube is auto-generating them for me... which is not the same as them being embedded by the uploader.
I know from experience that if the uploader included subtitles, checking the "Embed subtitles" box in ytdlp-interface definitely will produce a file with those subtitles included.

**Comment by alekssmitt** [comment]
yes yes, that's right, these are automatically generated subtitles and I meant it, because sometimes you need subtitles in your native language instead of embedded subtitles.

**Comment by githottub** [comment]
But ytdlp can only download and include embedded subtitles. Automatically generated ones are not part of the video file thus there is nothing for ytdlp to download.

**Comment by alekssmitt** [comment]
Now it's all completely clear to me, I just didn't know it was a ytdlp flaw

**Comment by Hyperi0n1337** [comment]
Hello. I wanted to ask about this, I cant seem to download subs. for example this vid https://www.youtube.com/watch?v=xzHhZh7F25I

regardless of 'embed subtitles' clicked on, and the prefered output format I choose, it doesn't yield subs.

But with my bat script which uses yt-dlp it works:

cd C:\Users\[Username]\Desktop\Youtube
:loopstart
set /p link=Enter link:
yt-dlp -i --write-auto-sub --embed-subs --sub-lang en_US,en-US,en --convert-subs srt --embed-thumbnail --no-cache-dir --add-metadata -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" --merge-output-format mp4 %link%
goto loopstart

any ideas why?
