### ISSUE TITLE
Add About tab to Settings window

### ISSUE THREAD

**Issue by Korb** [ErrorFlynn/ytdlp-interface#165]
It would be convenient for me if in the Settings window, in addition to the tabs "yt-dlp", "SponsorBlock", "Queuing", "Interface" and "Updater", there was a tab with web links to ytdlp-interface resources and a list of used libraries with their versions.

**Comment by ErrorFlynn** [comment]
>a tab with web links to ytdlp-interface resources

What resources did you have in mind? All I can think about is the link to the GitHub repository.

**Comment by Korb** [comment]
> What resources did you have in mind? All I can think about is the link to the GitHub repository.

If you have nothing else but GitHub, then yes, a link to it. You added it. Thank you for fulfilling my humble request. Hope this made your app a little better.
