### ISSUE TITLE
[Question] How to download "Up to" resolution

### ISSUE THREAD

**Issue by christubuntu** [ErrorFlynn/ytdlp-interface#174]
I'm new to this software and I can clearly see where to set different resolutions, but I'm facing an issue where downloading a playlist with videos of mixed resolutions ( some are 720o and other 480p). how do i set it so it 1st fetches the 720p and then download 480p is the former is not available?
for ex, this playlist (https://www.youtube.com/playlist?list=PLmgR2eygrwdh-izYr2p6Zc1TiWRjfNyh3) has videos with 720p and 480p. If I set resolution to 720p, it just skips the 480p ones.

**Comment by ErrorFlynn** [comment]
Just set the preferred resolution (in `Settings -> yt-dlp`) to 720p, and don't request a specific format from the formats list. The next highest available resolution will be downloaded when 720p is not available.

If you select a specific format in the formats list, yt-dlp will only download that one format and issue an error when the format is not available.

If you click the square button with the info icon in the upper-right corner of `Settings -> yt-dlp`, a window pops up with some info that attempts to explain this stuff.
