### ISSUE TITLE
[feature request] streamline the GUI

### ISSUE THREAD

**Issue by geextahslex** [ErrorFlynn/ytdlp-interface#179]
Hi, I just wanted to say that it would be nice not only to add "features" but also streamline the GUI as I think this one is a bit cluttered, too much stuff on the main window. Here are some suggestions

This is a clean layout
![playlist_jpg](https://github.com/user-attachments/assets/98925298-3d6e-4c9c-9b39-339b637ad904)

this is a bit confusing
![340518580-86fd2013-4247-4f1e-8038-334ed31a3d4e](https://github.com/user-attachments/assets/0c2b99a1-8f23-4205-b13b-ba6a47df187a)

**Comment by ErrorFlynn** [comment]
You can click the collapse/expand button to hide/show the download options (the `^` interface element below the "Queue actions" button). I have no plans to declutter the interface beyond that.
