### ISSUE TITLE
Sign in error.

### ISSUE THREAD

**Issue by uchr4l** [ErrorFlynn/ytdlp-interface#181]
[GUI] got error executing command line: yt-dlp.exe --no-warnings -j -o "%(title)s.%(ext)s" "https://www.youtube.com/watch?v=bzyMLoSwYvk"

ERROR: [youtube] bzyMLoSwYvk: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by ErrorFlynn** [comment]
Try using `Settings -> yt-dlp -> Load cookies from browser`. That will cause yt-dlp to authenticate using the cookies from the browser you specify (you will need to be logged in to YouTube in that browser).

I don't know why it requires you to authenticate for that video, it doesn't for me. Use the "load cookies" feature sparingly, only when needed (to minimize any potential risk of having your YT account banned).
