### ISSUE TITLE
Interface doesn't know what to do with multilanguage-audio Youtube videos

### ISSUE THREAD

**Issue by Yoksven** [ErrorFlynn/ytdlp-interface#188]
I'm on 2.14.1. Always get an error for videos that have multiple language tracks (requested format is not available. use --list-formats for a list of available formats). Examples:

https://www.youtube.com/watch?v=bKjfw77cxeQ
https://www.youtube.com/watch?v=77dZGh34aX8

These videos can be downloaded with yt-dlp through the command line, but they have a giant list of funky audio codes and it's a bit of a pain to find the right one, so the interface would be very helpful here, but it can't even get to the part where you can select formats. Errors out right away.

**Comment by ErrorFlynn** [comment]
I was unable to reproduce this, everything works fine for me. If this still happens, can you paste the command line that the program uses? Click the `Show output` button, then right-click on the output and select `Copy to clipboard`.

Sorry for the late response.

**Comment by Yoksven** [comment]
[GUI] got error executing command line: yt-dlp.exe --no-warnings -j -o "%(title)s.%(ext)s" -S "res:720,vext:webm,aext:opus,vcodec:vp9" "https://www.youtube.com/watch?v=bKjfw77cxeQ"

ERROR: [youtube] bKjfw77cxeQ: Requested format is not available. Use --list-formats for a list of available formats

**Comment by ErrorFlynn** [comment]
I can't explain it. Do you still get the error if you run that command in a command prompt window? I don't imagine you would, but I'm out of ideas.

**Comment by Yoksven** [comment]
I do get the same error in a command prompt with `yt-dlp.exe --no-warnings -j -o "%(title)s.%(ext)s" -S "res:720,vext:webm,aext:opus,vcodec:vp9" "https://www.youtube.com/watch?v=bKjfw77cxeQ"`. If I actually add `--list-formats` at the end, like it asks, I get the list like normal. [Screenshot](https://i.ibb.co/KjwB3xd/Illustration.jpg).

It could have something to do with the fact that I'm running Windows 7. I'm currently using VxKex to run Win10 programs on it, but I had this problem even before I've started using VxKex (before Win10 became a requirement for yt-dlp or this interface). If that's the reason, then I'm expecting it to not have a solution, since that's just the experience of living on Win7 in 2024.

**Comment by ErrorFlynn** [comment]
That has to be it, even though VxKex lists Python as a compatible application. Maybe the Python interpreter that's embedded in yt-dlp.exe is different somehow (just my speculation, I'm not familiar with Python).

It looks like I'll have to make a build that uses the yt-dlp fork that supports Win7 (https://github.com/nicolaasjan/yt-dlp). In the meantime, you can download [yt-dlp_win7.exe](https://github.com/nicolaasjan/yt-dlp/releases/download/2024.12.16.072540/yt-dlp_win7.exe), then rename the file to `yt-dlp.exe`, and just replace the original yt-dlp.exe with it. As long as you don't use the interface to update yt-dlp (which would overwrite the Win7 version), it should work.

**Comment by Yoksven** [comment]
Well, the problem was there even before VxKex (I honestly don't think I've ever downloaded a multi-language-track video successfully with the interface), but I'm okay with it not getting fixed if Win7 is the issue here. Older builds of yt-dlp are not an option. There has been a couple of serious problems with Youtube changing things recently that were fixed just like a week or two ago. That was the whole reason I had to bust out VxKex.

It's fine. It's just multi-language videos that I have to use the command line for. I'll live.

**Comment by ErrorFlynn** [comment]
>Older builds of yt-dlp are not an option.

The fork I linked (https://github.com/nicolaasjan/yt-dlp) is always up to date with the upstream repository (https://github.com/yt-dlp/yt-dlp). It just uses a custom Python build (that supports Windows 7) for [yt-dlp_win7.exe](https://github.com/nicolaasjan/yt-dlp/releases/latest/download/yt-dlp_win7.exe).

**Comment by Yoksven** [comment]
If I remove `-j` from the prompt - it works in the command line. I'm not sure why, because on single language videos `-j` works fine and spits out json, like it should. Either way, it seems like it's not the interface problem, but yt-dlp problem. And they will not bother with it, because Win7 isn't supported anymore. So. The end.

**Comment by ErrorFlynn** [comment]
>Either way, it seems like it's not the interface problem, but yt-dlp problem.

Well, I just tested the command in a Windows 7 VM with `yt-dlp_win7.exe`, and it worked. So it must be something with your environment, but I can't imagine what. Weird!
