### ISSUE TITLE
'Max concurrent downloads' setting being ignored

### ISSUE THREAD

**Issue by azumukupoe** [ErrorFlynn/ytdlp-interface#25]
all the items in the queue are being downloaded at once even though I have set 'Max concurrent downloads' to 1

**Comment by ErrorFlynn** [comment]
I can't reproduce this issue on my end (using version 1.6.3).

I added 2 items to the queue (YouTube videos), then I right-clicked the queue and selected `Start item #1`. The program then started item 1, and only started item 2 after 1 finished. The same thing happened when I started item 1 with the button.

Can you tell me the exact steps you take to produce the issue on your end?

**Comment by ErrorFlynn** [comment]
> so I'm not supposed to use `Start all` from the `Queue actions` menu?

No, `Start all` starts all the queue items, regardless of the `Max concurrent downloads` limit. If you have 1000 queue items, they will all start. I can see your logic, you thought that `Start all` would start all the items within the "max concurrent" limit, but that's not how it works!

You have to start an individual item, and then if the limit is higher than 1, the program will automatically start other queue items until the limit is reached. If not, then only that individual item is started.
