### ISSUE TITLE
Youtube video causes a crash when getting metadata

### ISSUE THREAD

**Issue by n-kalosha** [ErrorFlynn/ytdlp-interface#26]
https://www.youtube.com/watch?v=nJ6tidrzxqM 

Gets added to the queue, but soon crashed when trying to get metadata.

Calling yt-dlp from the command-line works with no issues. 

Windows 10 64 bit, latest versions of everything.

**Comment by ErrorFlynn** [comment]
Thanks for reporting this, I've released v1.6.4 which fixes the crash.
