### ISSUE TITLE
崩溃了 gif

### ISSUE THREAD

**Issue by 1353604736** [ErrorFlynn/ytdlp-interface#28]
![动画02](https://user-images.githubusercontent.com/12869582/208570327-6c84078f-f760-4550-adc4-187df489509e.gif)

**Comment by megabugman** [comment]
yeah, the/a crash is reproducible.
![bug21](https://user-images.githubusercontent.com/17204819/208674950-14b48bcc-5ce8-484a-97ca-72b840e2f1f1.gif)

to reproduce, simply click without adding any link to change to output.

**Comment by ErrorFlynn** [comment]
I will look into both crashes, thank you for reporting them.
