### ISSUE TITLE
aria2c integration

### ISSUE THREAD

**Issue by AHOHNMYC** [ErrorFlynn/ytdlp-interface#3]
yt-dlp can use [aria2c](https://aria2.github.io/manual/en/html/README.html) as external downloader. The main reason of using aria2c is download thread parallelization. Can you please add detecting aria2c on `%PATH%` (or selecting manually in Settings) and corresponding changes in UI:
* Checkbox "Use aria2c"
* Integer input "Download threads count"

Command with this options looks like: `yt-dlp --external-downloader "aria2c" --external-downloader-args "-j 8" ...`

**Comment by ErrorFlynn** [comment]
I'll look into it, thanks for the suggestion.

**Comment by AHOHNMYC** [comment]
I'm not sure about options, but completely sure that aria2c utilizes maximum bandwidth.
Rationale is difference in download speed. Maximum I saw up to 5 times. You may check it by yourself on any service. Again, don't know about services limitation their proxy server settings and other. I just saw times faster downloading.
