### ISSUE TITLE
Issues when downloading complete YT channel

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#34]
Hi, I noticed some issues when downloading a complete YT channel like

https://www.youtube.com/@solidbugs

Overall the application seems to work and download all videos for the channel.
But the following issues occurred while downloading:

1. At the beginning the Media title was empty
2. Some vids later the Media title was showing always the first and second maybe third video title but after completing the download the Media Title did not update and kept showing the first video titles
3. I noticed the Status went up to +1000% in a case

Hopefuly you can reproduce the issues...

**Comment by ErrorFlynn** [comment]
This didn't make it into v1.8, but I'll look into it and see if I can add support in the next version. Thanks for the feedback.
