### ISSUE TITLE
"error yt-dlp failed to get info (see output)" with any YouTube URL

### ISSUE THREAD

**Issue by azumukupoe** [ErrorFlynn/ytdlp-interface#36]
```
GUI: yt-dlp is unable to process queue item #1 (output below)


Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```
I can download the videos but I can't choose video and audio streams due to this error

**Comment by ErrorFlynn** [comment]
Can you provide a screenshot of the settings and download options you're using?

**Comment by ErrorFlynn** [comment]
Never mind, I think I figured it out. The issue seems to happen when the `Prefer a higher framerate` checkbox is unchecked in the settings.
