### ISSUE TITLE
Some issues about not being able to open and crashing.

### ISSUE THREAD

**Issue by 1353604736** [ErrorFlynn/ytdlp-interface#40]
Some issues about not being able to open and crashing.
![699](https://user-images.githubusercontent.com/12869582/224467573-a571df6e-5f57-46ee-a1ca-6e4d566c803f.gif)

**Comment by MODKILLER1001** [comment]
I am also having this issue.

**Comment by MODKILLER1001** [comment]
@1353604736 I figured out the issue. Delete ytdlp-interface.json and open it

**Comment by ErrorFlynn** [comment]
I am unable to reproduce the crash (I tried both on Windows 11 and Windows 10, and I even switched to Chinese language on Windows 10). Does it still crash if you don't use `Program Files`? For example, `D:\ytdlp-interface`.

**Comment by 1353604736** [comment]
> I am unable to reproduce the crash (I tried both on Windows 11 and Windows 10, and I even switched to Chinese language on Windows 10). Does it still crash if you don't use `Program Files`? For example, `D:\ytdlp-interface`.

I haven’t figured out the logic of his crash either. The path has not changed. Now it’s not crashing normally and is being observed continuously.

**Comment by ErrorFlynn** [comment]
Is v2.3.0 still crashing?

**Comment by 1353604736** [comment]
> Is v2.3.0 still crashing?

Well now, 2.3.0 is no longer crashing
