### ISSUE TITLE
Feature request: Add the option to insert metadata to downloaded file

### ISSUE THREAD

**Issue by hermaherp** [ErrorFlynn/ytdlp-interface#43]
As of current, the program does not have any visible check for the "--add-metadata" command argument, and thus has to be manually added for all links in the download queue through the "Each item in the queue has its own download options" check and then inserting the argument in the Custom arguments space. Adding the option would be a good Quality of Life feature to remove unnecessary work that can be automated

**Comment by ErrorFlynn** [comment]
>and thus has to be manually added for all links in the download queue through the "Each item in the queue has its own download options" check

I think you're misunderstanding what `Each item in the queue has its own download options` does. If that's checked, then each item in the queue can have options that are different from those of the other queue items. If it's unchecked, then all queue items share common options, which is what you want in your case.

If you want to use `--add-metadata` for all queue items, then uncheck `Each item in the queue has its own download options`, and use `--add-metadata` as a custom argument.
