### ISSUE TITLE
Extra data on queue table?

### ISSUE THREAD

**Issue by airworksman** [ErrorFlynn/ytdlp-interface#44]
Hi, great GUI and thanks for providing it on scoop as well.

I am trying a few other GUIs and one thing I feel missing is being able to see what video and audio is selected by yt-dlp by default. In the queue table, is it possible to show extra data such as the video/audio format and size? Not sure if this data is available yet, or only when you actually start downloading.

My use case is that while I do prefer a certain default format, sometimes I change my mind based on seeing the format and sizes. For example, I might prefer default 4k video size, but if the file size is too big, I might settle for 1440p instead. Similarly I might prefer webm, but see that it's not available, I might just decide to not download it at all.

I think it'd be a lot more convenient this way instead of clicking select formats for each item. The only issue is whether it takes up too much column space if you're not fullscreened. Maybe an idea is to show an icon for the video and audio and when you hover over them it shows the text. Similarly this could be done for the website showing a favicon to save space?

Any thoughts on this? Thanks.

**Comment by ErrorFlynn** [comment]
>Hi, great GUI and thanks for providing it on scoop as well.

Hi, I have no idea what "scoop" is! I'm only releasing on GitHub, if you see `ytdlp-interface` anywhere else, it wasn't me.

>Not sure if this data is available yet, or only when you actually start downloading.

I just checked, and the data is available (yt-dlp is pretty amazing). I'll see what I can do, thanks for the feedback.

**Comment by airworksman** [comment]
No problem, scoop.sh is a command line installer for Windows, kind of similar to a package manager.
