### ISSUE TITLE
? Output template affects downloading single videos ? but not playlist items ...

### ISSUE THREAD

**Issue by altadr** [ErrorFlynn/ytdlp-interface#47]
Thank you very much for the info! 
So I could do some (a lot of ...) experimenting 
and some questions occurred ... 

Preface
Downloading e.g. this video https://www.youtube.com/watch?v=0jdJOo1i8Hk 
was no problem with the default output template, 
but failed  for me using my (admittedly a little bit special) one.  

[  Remark:
NB: In the following sometimes then '#'-character is used, 
this only refers to numbered items in the download parameters, 

it does not refer to any 'feature request: #n', 
only I don't know how to de-highlight and de-link these !  ]

_____________________________________________________________________

What makes things interesting: 
In the command line window it is downloaded without any problem, 
even with my possibly a bit unusual output template like 
>"C:\Users\av\Downloads\ErrorFlynn` - ytdlp-interface\yt-dlp.exe" -S "res:1080,vext:mp4,aext:m4a,fps" --trim-filenames 100  -P E:\YT -o "@ %(channel)s%(playlist_title&  in: |)s%(playlist_title|)s%(playlist_index& #|)s%(playlist_index|)d  '%(title)s%(alt_title& ~ |)s%(alt_title|)s' - %(upload_date>%Y-%m-%d)s  %(location& |)s%(location|)s %(duration>%Hh%Mm%Ss )s%(resolution)s id=%(id)s.%(ext)s" https://www.youtube.com/watch?v=0jdJOo1i8Hk

the file was downloaded perfectly. 

_____________________________________________________________________

The same parameters put into ytdlp-interface 

make the queue show:
Website: error_______Media title: yt-dlp failed to get info (see output)_______Status: error

Output:
GUI: yt-dlp is unable to process queue item #1 (output below)  .   .   .  .  .  .  .  [ concerning the '# 1' plz see the remark at the top ]
ERROR: Fixed output name but more than one file to download: @

[  Remark: The shown '@' is only the first character of the output template, 
exchanging this by any other doesn't change the behaviour ... , 

possibly the elements of the output template are interpreted as URLs ?  ]

After despite the error message clicking the 'Start download' button 
ytdlp-interface starts working, 

output shows now:
[GUI] executing command line: "C:\Users\av\Downloads\ErrorFlynn - ytdlp-interface\yt-dlp.exe" -S "res:1080,vext:mp4,aext:m4a,fps" --trim-filenames 100  -P E:\YT -o "@ %(channel)s%(playlist_title&  in: |)s%(playlist_title|)s%(playlist_index& #|)s%(playlist_index|)d  '%(title)s%(alt_title& ~ |)s%(alt_title|)s' - %(upload_date>%Y-%m-%d)s  %(location& |)s%(location|)s %(duration>%Hh%Mm%Ss )s%(resolution)s id=%(id)s.%(ext)s" https://www.youtube.com/watch?v=0jdJOo1i8Hk

[  Remark: This seems to be exactly, what I had tested on the command line successfully ? 
Do I miss something? ]

[  continued ...  ]
Usage: yt-dlp.exe [OPTIONS] URL [URL...]
yt-dlp.exe: error: invalid after_move print to file filename "%(channel)s%(playlist_title&": incomplete format key
Usage: yt-dlp.exe [OPTIONS] URL [URL...]
yt-dlp.exe: error: invalid after_move print to file filename "%(channel)s%(playlist_title&": incomplete format key
[GUI] yt-dlp.exe process has exited

and queuing shows:
Website: error_______Media title: yt-dlp failed to get info (see output)_______Status: done

subsequently in ytdlp-interface.json
    "unfinished_queue_items": [],

But no file has been downloaded.

_____________________________________________________________________

And, maybe even more interesting:

With exactly the same parameters in ytdlp-interface left unchanged, but 

using the playlist-URL 
https://www.youtube.com/playlist?list=PLrlXp3PlwgRI5OLvm3P91LJr1CYnO5TRD
and selecting in the playlist item #12,   .   .   .  .  .  .  .  [ concerning the '# 12' plz see the remark at the top ]

everything works fine!

Output:
[GUI] executing command line: "C:\Users\av\Downloads\ErrorFlynn - ytdlp-interface\yt-dlp.exe" -S "res:1080,vext:mp4,aext:m4a,fps" --trim-filenames 100    -P E:\YT -o "@ %(channel)s%(playlist_title&  in: |)s%(playlist_title|)s%(playlist_index& #|)s%(playlist_index|)d  '%(title)s%(alt_title& ~ |)s%(alt_title|)s' - %(upload_date>%Y-%m-%d)s  %(location& |)s%(location|)s %(duration>%Hh%Mm%Ss )s%(resolution)s id=%(id)s.%(ext)s" -I 12 --compat-options no-youtube-unavailable-videos https://www.youtube.com/playlist?list=PLrlXp3PlwgRI5OLvm3P91LJr1CYnO5TRD

[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLrlXp3PlwgRI5OLvm3P91LJr1CYnO5TRD
[youtube:tab] PLrlXp3PlwgRI5OLvm3P91LJr1CYnO5TRD: Downloading webpage
[download] Downloading playlist: All Episodes - 2-Stroke Carburetor Learning
[youtube:tab] Playlist All Episodes - 2-Stroke Carburetor Learning: Downloading 1 items of 60
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=0jdJOo1i8Hk
[youtube] 0jdJOo1i8Hk: Downloading webpage
[youtube] 0jdJOo1i8Hk: Downloading android player API JSON
[youtube] 0jdJOo1i8Hk: Downloading MPD manifest
[info] 0jdJOo1i8Hk: Downloading 1 format(s): 135-dash+140
[dashsegments] Total fragments: 15
[download] Destination: E:\YT\@ TheRepairSpecialist  in All Episodes - 2-Stroke Carburetor Learning #12  'Episode 12 Two-Stroke .' - 2016-10-09   00h01m16s 640x480 id=0jdJOo1i8Hk.f135-dash.mp4
[dashsegments] Total fragments: 1
[download] Destination: E:\YT\@ TheRepairSpecialist  in All Episodes - 2-Stroke Carburetor Learning #12  'Episode 12 Two-Stroke .' - 2016-10-09   00h01m16s 640x480 id=0jdJOo1i8Hk.f140.m4a
[Merger] Merging formats into "E:\YT\@ TheRepairSpecialist  in All Episodes - 2-Stroke Carburetor Learning #12  'Episode 12 Two-Stroke .' - 2016-10-09   00h01m16s 640x480 id=0jdJOo1i8Hk.mp4"
Deleting original file E:\YT\@ TheRepairSpecialist  in All Episodes - 2-Stroke Carburetor Learning #12  'Episode 12 Two-Stroke .' - 2016-10-09   00h01m16s 640x480 id=0jdJOo1i8Hk.f140.m4a (pass -k to keep)
Deleting original file E:\YT\@ TheRepairSpecialist  in All Episodes - 2-Stroke Carburetor Learning #12  'Episode 12 Two-Stroke .' - 2016-10-09   00h01m16s 640x480 id=0jdJOo1i8Hk.f135-dash.mp4 (pass -k to keep)
[download] Finished downloading playlist: All Episodes - 2-Stroke Carburetor Learning
[GUI] yt-dlp.exe process has exited

Queue:
Website: youtube.com_______Media title: [playlist] All Episodes - 2-Stroke Carburetor learning_______Status: done

File downloaded perfectly.

_____________________________________________________________________

Probably I made some mistake, but have no idea, which one(s) ...
What can I do to make it work on the single URL as perfectly as on the playlist URL item # 12, 
using my output template ?

**Comment by ErrorFlynn** [comment]
>Probably I made some mistake, but have no idea, which one(s) ...

You didn't, but I did. Congratulations, you found a bug! I have fixed it now, so this will no longer be an issue in the next version (which should be out soon).
