### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [ErrorFlynn/ytdlp-interface#5]
Hello,

First I would like to say that [ytdlp-interface](https://github.com/ErrorFlynn/ytdlp-interface) turned out to be a well-designed and very pleasant to use GUI fpr [yt-dlp](https://github.com/yt-dlp/yt-dlp), good work, thanks.

As of version [1.4.1](https://github.com/ErrorFlynn/ytdlp-interface/releases/tag/v1.4.1) program settings are saved in configuration file (**ytdlp-interface.json**) in **AppData**:

`C:\Users\User\AppData\Roaming\ytdlp-interface.json`

My request- when **ytdlp-interface** starts it should check its **program folder** for the configuration file, **ytdlp-interface.json**, and if it is there (next to the executable, **ytdlp-interface.exe**), it should use it to load and save settings without re-creating it in **AppData**.

I suppose an additional useful enhancement might be a new check box in **Settings**:

- **Portable mode**

which, if enabled, will save both the configuration file and the downloaded videos in program folder, so nothing will be written outside the program folder. This would be particularly convenient for using the program from external drives on other machines without leaving any traces behind (all data is saved in program folder)

Regards

**Comment by ErrorFlynn** [comment]
The reason the program uses %AppData% is because it might not have write access to its own folder. From the next version forward, the program will check if it has write access to the folder it is in, and will store the config file there if possible.

I will not be adding a "portable mode", but when selecting the download folder, the folder selection window will start in the program folder, so it will be very easy to select it.

Thanks for the feedback!

**Comment by smaragdus** [comment]
@ErrorFlynn 

Thank you for considering my ideas.

> The reason the program uses %AppData% is because it might not have write access to its own folder. From the next version forward, the program will check if it has write access to the folder it is in, and will store the config file there if possible.

Excellent! Any option to save configuration file in program folder is fine for me.

> I will not be adding a "portable mode", but when selecting the download folder, the folder selection window will start in the program folder, so it will be very easy to select it.

This is also fine.

Best regards!
