### ISSUE TITLE
ok.ru downloads closing the interface

### ISSUE THREAD

**Issue by ockr** [ErrorFlynn/ytdlp-interface#51]
something new started, just in the past week
if i try to start an ok.ru download, the interface closes.
i tried using an older version.
it didn't crash but it wouldn't download anything either.

**Comment by rumgum** [comment]
I have the same issue.

**Comment by ErrorFlynn** [comment]
Thanks for the reports, this will be fixed in the next version (should be out in a few days).

**Comment by rumgum** [comment]
awesome.
