### ISSUE TITLE
PLZ add PROXY configration

### ISSUE THREAD

**Issue by pein0saga** [ErrorFlynn/ytdlp-interface#55]
Need PROXY function

**Comment by l3xrom** [comment]
You can add it in custom arguments
# HTTP proxy
--proxy IP_ADDRESS:PORT

# SOCKS proxy
--proxy socks5://IP_ADDRESS:PORT

# SOCKS proxy with authentification
--proxy socks5://user:pass@IP_ADDRESS:PORT
