### ISSUE TITLE
Right click paste on custom arguments

### ISSUE THREAD

**Issue by JonnyThree** [ErrorFlynn/ytdlp-interface#56]
Hello thanks so much for the new update that add the possibility to choose custom formats on discoveryplus.com links. I have a small question, it's possible to add the paste shell for adding custom arguments in the main interface?

**Comment by ErrorFlynn** [comment]
You can click on the text box and press Ctrl+V to paste the arguments, but I can also add a context menu with the "paste" command, if that's what you're asking.

**Comment by JonnyThree** [comment]
> You can click on the text box and press Ctrl+V to paste the arguments, but I can also add a context menu with the "paste" command, if that's what you're asking.

yes i clearly know the ctrl+v keyboard command, but a simple mouse right click is more easy to do, thanks for your work in this excellent gui for yt-dlp
