### ISSUE TITLE
Slow Download speed on a youtube playlist

### ISSUE THREAD

**Issue by aphonsoeliasf** [ErrorFlynn/ytdlp-interface#58]
I'm using the software in my notebook Windows 10 with a wired connection and the download speed are too slow, i check if there's a problem with my connection but that's not the case, can someone help me with this issues. I took some screenshots from the connection and the software download speed to show the issue.
![ytdlp slow download](https://github.com/ErrorFlynn/ytdlp-interface/assets/29491462/5fee3d25-52d9-46e2-afbf-128f506ccf53)
![ytdlp interface](https://github.com/ErrorFlynn/ytdlp-interface/assets/29491462/0f405395-561a-4688-b868-b3df4b82eaaf)

**Comment by Korb** [comment]
@aphonsoeliasf, if you were in a country that started a war in Europe i would assume you were censored and in your case using a fast VPN outside your country would help. have you tried this workaround and did it help you get acceptable download speeds?

**Comment by aphonsoeliasf** [comment]
I run some tests about the network, it seems my ISP is slowing my speed
during the download. I live in Brazil, i enter in contact with them and
there's some block which is slowing the speed, i've been using a VPN and
solve this issue. Thanks for reply.

Em dom., 28 de jul. de 2024 às 15:45, Korb ***@***.***>
escreveu:
