### ISSUE TITLE
Sugestion. Add please container MKV and option download multiple audio

### ISSUE THREAD

**Issue by DajMiliona** [ErrorFlynn/ytdlp-interface#59]
Add container MKV and option download wideo witch multiple audio files and save to mkv container
Example: 
https://www.europarl.europa.eu/plenary/en/vod.html?mode=unit&vodLanguage=EN&playerStartTime=20230509-11:23:42&playerEndTime=20230509-11:27:41#
How to download wideo witch all audio and save to mkv container, or download wideo witch selected multiple audion  and save to mkv.

**Comment by ErrorFlynn** [comment]
There's no need to add the MKV option. Just use these custom arguments: `--audio-multistreams -f bestvideo+mergeall` (I have tested with the link you provided).

**Comment by DajMiliona** [comment]
I want to choose which languages ​​I want to download. It is possible to add multiple options in gui? I don't know commands for CLI
 I use Google translator. Thank you.

**Comment by ErrorFlynn** [comment]
I will make the GUI let you select multiple audio streams in the "select formats" window, but it may not always be possible to determine the language of each stream from its format name. For example, for the link you provided yt-dlp lists the audio formats as `audio-Original_Audio_9`, `audio-Original_Audio_8`, and so on. It would be up to you to determine which languages those are.
