### ISSUE TITLE
FFmpeg special version

### ISSUE THREAD

**Issue by trimechee** [ErrorFlynn/ytdlp-interface#6]
Hello, thank you very much for this wonderful and amazing software ! juste a question, I wonder if Ytdlp-interface uses the special version of FFmpeg to avoid bugs? because there is a special builds of FFmpeg for yt-dlp to fix some bugs, it will be great if  Ytdlp-interface  can add and update automatically this special builds of FFmpeg to fix some bugs for example

[Fix AAC HLS streams being truncated mid stream]

[Fix for YouTube's VP9 encodes with non-monotonous DTS]

https://github.com/yt-dlp/FFmpeg-Builds

**Comment by ErrorFlynn** [comment]
>I wonder if Ytdlp-interface uses the special version of FFmpeg

Yes, it does.

>it will be great if Ytdlp-interface can add and update automatically this special builds of FFmpeg

I'll look into the possibility of updating FFmpeg from the interface (not promising anything though!)

**Comment by trimechee** [comment]
Great ! Thank you very much :)

**Comment by trimechee** [comment]
Wonderful ! Thank you very much !
