### ISSUE TITLE
Can I help this app translate to another language?

### ISSUE THREAD

**Issue by PianCat** [ErrorFlynn/ytdlp-interface#61]
Can I help this app translate to another language?
I want to translate it to Chinese

**Comment by ErrorFlynn** [comment]
Not yet, unfortunately. The app doesn't have internationalization capability right now, but I do intend to add it at some point (I'll try to make it a high priority). Thanks for the interest.

**Comment by c-sanchez** [comment]
Hi @ErrorFlynn , I would also like to translate the application in Spanish.
I hope you can add support for localizations.
