### ISSUE TITLE
chapters are without name (2.2.2)

### ISSUE THREAD

**Issue by dardoor** [ErrorFlynn/ytdlp-interface#65]
In v2.2.2 the embedded chapters are not named. The same setting works fine in 1.9.2.

Example video: [https://www.youtube.com/watch?v=b1Fo_M_tj6w](https://www.youtube.com/watch?v=b1Fo_M_tj6w)

**Comment by ErrorFlynn** [comment]
This seems to be a bug with FFmpeg (known issue: https://github.com/yt-dlp/yt-dlp/issues/6859). Wait for a fix I guess, and in the meantime you can downgrade to the FFmpeg version included with v1.9.2.

I'll leave this issue open for now, for anyone else who may not be aware.

**Comment by ErrorFlynn** [comment]
The bug has finally been fixed, so I'm closing the issue.
https://trac.ffmpeg.org/ticket/10482
