### ISSUE TITLE
Concurrent Downloads Setting Does Not Apply

### ISSUE THREAD

**Issue by hl2guide** [ErrorFlynn/ytdlp-interface#79]
![concurrent downloads](https://github.com/ErrorFlynn/ytdlp-interface/assets/17044982/8df71b04-c98f-4f51-b200-6cc8ec15dec6)

The full list runs.

**Comment by githottub** [comment]
I think the queue is generally not working. For example, I pasted several URLs but only wanted to start downloading 1 of them so it would get the full bandwidth and finish first. So, I right-clicked on that URL and selected to start just it. But the others started also.

**Comment by ErrorFlynn** [comment]
I have not been able to reproduce these issues (I've tried multiple times, with different versions). Setting the max concurrent downloads to 4 always resulted in 4 downloads max running at a time, and selecting "Start item #n" always resulted in just that item starting.

**Comment by hl2guide** [comment]
I've done more testing and haven't run into this again since updating to 2.10.

Seems like it may have been resolved in the meantime.
