### ISSUE TITLE
[bandcamp] single track albums ignore per-site output template

### ISSUE THREAD

**Issue by azumukupoe** [ErrorFlynn/ytdlp-interface#86]
for example:

if I use below URLs as the input
https://pajjama.bandcamp.com/album/starch
https://pajjama.bandcamp.com/album/jane-papaya
https://pajjama.bandcamp.com/album/karakasa
https://pajjama.bandcamp.com/album/womb

they show up in the program as below
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/31339007/4d8c1121-d145-4bc8-a4e4-20aa344f0ce3)

when I go into the Settings view while selecting a single track album (ones missing [playlist] in the titles), default template setting is shown and if I modify it, the value gets saved as output_template in the ytdlp-interface.json

**Comment by ErrorFlynn** [comment]
Yes, the code deliberately revokes the "playlist status" of albums that contain a single track, so the special output template and the `Put playlists in their own folders` setting no longer apply (that was the behavior that made sense to me at the time). I'm not sure if I should make this behavior optional, or just remove it altogether, but either way I will address it in the next version.
