### ISSUE TITLE
[Feature Request] File name modification

### ISSUE THREAD

**Issue by LurkerFellow** [ErrorFlynn/ytdlp-interface#88]
Please consider adding support for custom file names for each download. (Along the lines of Windows' Save As dialog box.)

### More Detail:
My suggestion is that, on a per-queue-item basis, there also be an option to edit the file name (just as the Save As dialog box when downloading whatever file via a web browser).

For users that enable "Each queue item has its own download options" in the settings: Although a different download folder can currently be selected for _each_ queue item, chances are that someone selecting a separate folder for each queue item may very well want to edit each video's file name too. Currently, the saved file name will be the title appearing on YouTube (which, of course, can always be renamed in File Explorer following completion of each download).

### How it may appear in Settings
I'd suggest programming it as default behavior of the app, but if this choice is instead just another option I'd propose that it be added to the Settings as follows: In the Queuing section, have another line (where arrow is in image) to check/uncheck the new option: **"Choosing a queue item's download location also allows editing the file name"**. This extra option should be unavailable/greyed-out if the user didn't also enable "Each queue item has its own download options."
![Screenshot0](https://github.com/ErrorFlynn/ytdlp-interface/assets/139586704/a0a90c50-1d8f-4d22-bad9-da5c04a3604c)

### Implementation
One way of implementing the choice would be that instead of "Download folder" (underlined in image) it read "Download location" and, besides allowing navigation to the desired folder, it also allow the user to edit the file name or leave it unchanged.
![Screenshot](https://github.com/ErrorFlynn/ytdlp-interface/assets/139586704/e055d39c-389c-4ea2-b099-21d677a88f14)

An alternate implementation would be that, under the "Choose folder..." button (as in image), another button be added to **"Choose folder and file name..."**.
![Screenshot3](https://github.com/ErrorFlynn/ytdlp-interface/assets/139586704/cc41639f-8a93-418d-9bad-0ff2ccf28082)

Either way though, clicking the big "Apply options to all queue items" button should _exclude_ the file name (which, obviously, can't be identical across the multiple items).

Thanks for your consideration

**Comment by ErrorFlynn** [comment]
Thank you for the thoughtful suggestions. After almost a year (sorry about that), version 2.12 adds the `Choose folder and filename` menu command. The chosen file name is not displayed alongside the folder (for technical reasons), but you can see it as a tooltip when you hover the mouse over the folder.
