### ISSUE TITLE
[Bug] Snap Windows To Screen Edge

### ISSUE THREAD

**Issue by githottub** [ErrorFlynn/ytdlp-interface#89]
Version 2.5.0. 

This setting still performs its function even when unchecked. The bug is reproduceable for me. Open settings window, move it to center of screen, restart, settings window is snapped to screen edge even though the setting is unchecked.

**Comment by megabugman** [comment]
not reproducible for me. snap to screen edges works as expected, intermediately after setting the checkbox

**Comment by githottub** [comment]
BUT what happens after RESTART. For me, even though the setting is UNchecked, after restart the settings window still snaps to screen edge rather than being in the middle of the screen where I left it before the last exit.

**Comment by megabugman** [comment]
not reproducible, setting is kept after restart.
close the app, rename "ytdlp-interface.json" to start virginal then try again. 
in case not working check the setting "cbsnap": true or false in the file.

**Comment by githottub** [comment]
Maybe it depends on the screen resolution. The PC that repeatedly exhibits the problem is 1920x1080. But I tried it on another PC with an ultrawide monitor and it doesn't exhibit the problem.

**Comment by ErrorFlynn** [comment]
>after restart the settings window still snaps to screen edge rather than being in the middle of the screen where I left it before the last exit

This is a little confusing, are you saying that when it pops up, the settings window is positioned such that it's touching the edge of the screen? When it pops up, the settings window is programmed to always appear centered relative to the main window (not necessarily in the middle of the screen, or where you left it last time).

**Comment by ErrorFlynn** [comment]
I just experienced this bug on a Windows 7 system at 1080p desktop resolution, and 150% scaling factor. The settings window does touch the right screen edge when it pops up, and when moving it with the mouse it's displaced rightward and downward by a number of pixels, instead of staying with the cursor.

I will look into fixing this when I have time.

**Comment by ErrorFlynn** [comment]
This should be fixed in v2.6.0 (let me know if it isn't), so I'm closing the issue.
