### ISSUE TITLE
Sponsor Block Support

### ISSUE THREAD

**Issue by gandhamvishnu** [ErrorFlynn/ytdlp-interface#9]
Please enable sponsor block support to download videos without sponsor sections

**Comment by ErrorFlynn** [comment]
I'm aware of sponsorblock, but I don't consider it a priority (meaning I _might_ add it as an explicit feature of the interface at some point in the future). For now, you can use the "custom arguments" feature to use sponsorblock, especially with the upcoming enhancement in v1.5 (it will remember multiple sets of arguments you can select from). That's what I do myself (I add `--sponsorblock-mark intro,outro,filler --sponsorblock-remove sponsor` as custom arguments).
