### ISSUE TITLE
Add CTRL+A to select all downloads

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#96]
for keyboard lovers.

1 CTRL+A to select all downloads
2. Pressing del would then remove them all

This way, you do not have to take your finger off the keyboard.

**Comment by githottub** [comment]
Yes, I'd also like to have this capability. It would be a huge improvement to having to delete completed downloads 1 at a time.

**Comment by ErrorFlynn** [comment]
>It would be a huge improvement to having to delete completed downloads 1 at a time.

You don't have to remove completed items one at a time, you can right-click on the queue and select `Clear completed`, which removes all completed items.

**Comment by githottub** [comment]
Thanks for the info.
